[package]
name = "dictate"
version = "0.1.0"
edition = "2021"
authors = ["Amirabbas Fazelinia <utilyre@proton.me>"]
license = "MIT"
description = "Simple CLI utility for looking up words in dictionaryapi.dev"
repository = "https://github.com/utilyre/dictate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
colored = "2"
clap = { version = "4.1.4", features = ["derive"] }
textwrap = { version = "0.16", features = ["terminal_size"] }
terminal_size = "0.2.5"
