[package]
name = "dictate"
version = "0.5.0"
edition = "2021"
authors = ["Amirabbas Fazelinia <utilyre@proton.me>"]
license = "MIT"
description = "Simple CLI utility for looking up words in online dictionary"
repository = "https://github.com/utilyre/dictate"

[dependencies.atty]
version = "0.2"

[dependencies.clap]
version = "4.1"
features = ["derive"]

[dependencies.colored]
version = "2.0"

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.textwrap]
version = "0.16"
features = ["terminal_size"]

[dependencies.tokio]
version = "1.25"
features = ["full"]

[dependencies.xdg]
version = "2.4"
